module.exports.descriptors = [
    'Spacious',
    'Colorful',
    'Inviting',
    'Ample',
    'Lively',
    'Active',
    'Silent',
    'Vibrant',
    'Abundant',
    'Eclectic',
    'Misty',
    'Exciting',
    'Dynamic',
    'Expansive',
    'Refreshing',
    'Joyous',
    'Dusty',
    'Accessible'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]